import { Inter } from "next/font/google";
import "./globals.css";
import { useSearchParams } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const searchParams = useSearchParams();
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
